# Generated by Django 3.1.7 on 2021-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='catchphrase',
            field=models.CharField(max_length=100),
        ),
    ]
